services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-tracker-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1\
      # - DASHBOARD_API_KEY=${DASHBOARD_API_KEY}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always